[package]
name = "ktee"
version = "0.1.0"
authors = ["Xavier Stevens <xavier@mystobreak.com>"]

[dependencies]
clap = "*"
kafka = { git="https://github.com/spicavigo/kafka-rust" }

[profile.release]
lto = true
